"use strict";

const { suite } = require("../harness");
const { PROJECT_MINIMAL, decide } = require("./_ctx");
const rule = require("../../core/guards/commit-message");

suite("guards/commit-message", ({ test, eq }) => {
  const cases = [
    // --- positive: one per table row in RULES.md
    {
      label: "a co-author trailer denies",
      command: 'git commit -m "Add feature" -m "Co-Authored-By: Someone <someone@example.com>"',
      want: "deny",
    },
    {
      label: "a generated-by signature denies",
      command: 'git commit -m "Generated with [Some Tool] a great feature"',
      want: "deny",
    },
    { label: "a robot emoji in the message denies", command: 'git commit -m "Add feature \u{1F916}"', want: "deny" },
    { label: "--no-verify denies", command: 'git commit -m "quick fix" --no-verify', want: "deny" },
    { label: "--no-gpg-sign denies", command: 'git commit -m "quick fix" --no-gpg-sign', want: "deny" },
    { label: "a conventional-commit prefix denies by default", command: 'git commit -m "feat: add thing"', want: "deny" },
    { label: "a scoped, breaking conventional prefix also denies", command: 'git commit -m "fix(auth)!: patch it"', want: "deny" },
    { label: "a ticket id in the subject denies", command: 'git commit -m "Fix crash on load #12345"', want: "deny" },
    {
      label: "the field-regression commit denies: a ticket id leading the subject",
      command: 'git commit -m "#31921 - Probe screen summary chip data"',
      want: "deny",
    },
    {
      label: "a staged protected path asks, per the entry's action",
      command: 'git commit -m "Update UI"',
      git: { staged: ["src/pages/Home.tsx"] },
      want: "ask",
    },
    {
      label: "a trailer in the second -m paragraph denies, not only the first",
      command: 'git commit -m "Add feature" -m "Co-Authored-By: Someone <someone@example.com>"',
      want: "deny",
    },
    {
      label: "a co-author trailer supplied via -F denies",
      command: "git commit -F /tmp/msg.txt",
      files: { "/tmp/msg.txt": "Update UI\n\nCo-Authored-By: Someone <someone@example.com>" },
      want: "deny",
    },
    {
      label: "a conventional prefix supplied via --file= denies",
      command: "git commit --file=/tmp/msg.txt",
      files: { "/tmp/msg.txt": "feat: add thing" },
      want: "deny",
    },
    {
      label: "a ticket id supplied via -F denies",
      command: "git commit -F /tmp/msg.txt",
      files: { "/tmp/msg.txt": "Fix crash on load #12345" },
      want: "deny",
    },

    // --- negative: ordinary daily commits
    { label: "a plain subject passes", command: 'git commit -m "Key screen-object coordination state by scope"', want: "pass" },
    { label: "amending without editing passes", command: "git commit --amend --no-edit", want: "pass" },
    {
      label: "mentioning the trailer phrase in prose, without a colon, passes",
      command: 'git commit -m "Note: this project never adds a co-authored-by trailer to commits"',
      want: "pass",
    },
    {
      label: "mentioning a number without a leading # passes",
      command: 'git commit -m "Fixes issue 12345 reported by QA"',
      want: "pass",
    },
    { label: "a short numeric hash below the ticket-id threshold passes", command: 'git commit -m "See #12 for details"', want: "pass" },
    { label: "an unrelated command passes", command: "git push origin feature/task_1_thing", want: "pass" },
    { label: "the word fix mid-sentence is not a conventional prefix", command: 'git commit -m "Quick fix for the login bug"', want: "pass" },
    {
      label: "a staged file that is not protected passes",
      command: 'git commit -m "Update UI"',
      git: { staged: ["src/other.ts"] },
      want: "pass",
    },
    {
      label: "a staged path matching Home.tsx stays silent when protectedPaths is not configured",
      command: 'git commit -m "Update UI"',
      git: { staged: ["src/pages/Home.tsx"] },
      project: PROJECT_MINIMAL,
      want: "pass",
    },
    {
      label: "a trailer phrase in prose, with other words before it on the line, passes",
      command: 'git commit -m "Document policy: never write Co-Authored-By: trailer in commits"',
      want: "pass",
    },
    {
      label: "a generated-by phrase in prose, with other words before it on the line, passes",
      command: 'git commit -m "Nightly report generated by [system] job succeeded"',
      want: "pass",
    },
    {
      label: "a message that only mentions the -F flag in prose does not evade via a phantom file read",
      command: 'git commit -m "reference the -F flag in docs"',
      want: "pass",
    },
    {
      label: "a -F path that cannot be read asks instead of failing open",
      command: "git commit -F /tmp/msg.txt",
      want: "ask",
    },
    {
      label: "a -F path outside the repo boundary asks instead of failing open",
      command: 'git commit -F "C:/outside/msg.txt"',
      want: "ask",
    },
    {
      label: "-F - with no heredoc to read back from asks instead of failing open",
      command: "git commit -F -",
      want: "ask",
    },
    {
      label: "a co-author trailer piped via -F - through an inline heredoc still denies",
      command: 'git commit -F - <<\'EOF\'\nAdd thing\n\nCo-Authored-By: Someone <someone@example.com>\nEOF',
      want: "deny",
    },
    {
      label: "a plain message piped via -F - through an inline heredoc passes",
      command: "git commit -F - <<'EOF'\nUpdate UI\nEOF",
      want: "pass",
    },
    {
      label: "--no-verify still denies even when the -F - message can't be read back",
      command: "git commit -F - --no-verify",
      want: "deny",
    },

    // --- evasion
    { label: "compound statement: cd then commit with a bad prefix", command: 'cd repo && git commit -m "feat: add thing"', want: "deny" },
    { label: "a global git flag before commit", command: 'git -c user.name=x commit -m "feat: add thing"', want: "deny" },
    { label: "semicolon-separated statements", command: 'git fetch; git commit -m "feat: add thing"', want: "deny" },
    { label: "-am combines stage-all with -m, and still denies a bad prefix", command: 'git commit -am "feat: add thing"', want: "deny" },
    { label: "-am with a ticket id still denies", command: 'git commit -am "Fix crash on load #12345"', want: "deny" },
    { label: "--message is the long spelling of -m", command: 'git commit --message "feat: add thing"', want: "deny" },
    {
      label: "evasion: a conventional-prefix commit hidden inside a bash -c nested shell",
      command: `bash -c 'git commit -m "feat: add thing"'`,
      want: "deny",
    },
    {
      label: "evasion: a co-author trailer hidden inside a PowerShell -Command nested shell",
      command: 'powershell -Command "git commit -m \'Add feature\' -m \'Co-Authored-By: Someone <someone@example.com>\'"',
      want: "deny",
    },
    {
      label: "evasion: --no-verify hidden inside a sh -c nested shell",
      command: `sh -c 'git commit -m "quick fix" --no-verify'`,
      want: "deny",
    },
    {
      label: "evasion: an IFS-joined -m still denies a bad prefix",
      command: 'git commit -m${IFS}"feat: add thing"',
      want: "deny",
    },
    {
      label: "evasion: an ANSI-C quoted message still denies a bad prefix",
      command: "git commit -m $'feat: add thing'",
      want: "deny",
    },

    // --- override clamp
    {
      label: "an ask override softens the conventional-prefix denial",
      command: 'git commit -m "feat: add thing"',
      want: "ask",
      overrideSpec: { "commit-message": { action: "ask" } },
    },
  ];

  for (const c of cases) {
    test(c.label, () => {
      const got = decide(rule, {
        command: c.command,
        project: c.project,
        git: c.git,
        files: c.files,
        overrideSpec: c.overrideSpec,
      });
      eq(got, c.want, c.label);
    });
  }

  test("conventionalPrefix: ask softens instead of denying", () => {
    const got = decide(rule, {
      command: 'git commit -m "feat: add thing"',
      project: { commitMessage: { conventionalPrefix: "ask" } },
    });
    eq(got, "ask");
  });

  test("conventionalPrefix: off silences the conventional-prefix check", () => {
    const got = decide(rule, {
      command: 'git commit -m "feat: add thing"',
      project: { commitMessage: { conventionalPrefix: "off" } },
    });
    eq(got, "pass");
  });
});
