"use strict";

/**
 * Table-driven suite for `file-size-limit`.
 */

const { suite } = require("../harness");
const { PROJECT_MINIMAL, decide } = require("./_ctx");
const rule = require("../../core/guards/file-size-limit");

/**
 * Builds source content with an exact number of lines.
 *
 * @param {number} n The number of lines to produce.
 * @returns {string} `n` newline-joined lines, no trailing newline.
 */
function linesOf(n) {
  return Array.from({ length: n }, (_, i) => `const x${i} = ${i};`).join("\n");
}

const OVER_ASK = linesOf(1600); // above the default 1500-line ask threshold
const UNDER_ASK = linesOf(1200); // above the 1000-line warn default, still under ask
const SMALL = linesOf(20);

const CASES = [
  // positive
  {
    label: "a plain source file past the default ask threshold asks",
    ctx: { toolName: "Write", filePath: "/repo/src/services/big.ts", content: OVER_ASK },
    want: "ask",
  },
  {
    label: "an already-oversized file growing further still asks",
    // The direction check must not turn into a blanket exemption for every
    // file that is already too big: growing one is exactly what this rule is
    // for.
    ctx: {
      toolName: "Edit",
      filePath: "/repo/src/services/huge.ts",
      content: linesOf(1700),
      files: { "/repo/src/services/huge.ts": linesOf(1600) },
    },
    want: "ask",
  },
  {
    label: "a write that leaves an oversized file shorter passes — splitting it is the fix, not the offence",
    // Measured case: an agent lifting a shared helper out of a 1808-line
    // component was stopped by this rule mid-refactor. The resulting file is
    // still over the threshold, and that is fine — it is moving the right
    // way, which is all a file that size can do in one step.
    ctx: {
      toolName: "Edit",
      filePath: "/repo/src/components/SearchToolbar.tsx",
      content: linesOf(1700),
      files: { "/repo/src/components/SearchToolbar.tsx": linesOf(1808) },
    },
    want: "pass",
  },
  {
    label: "a brand-new oversized file still asks — there is no previous size to be shrinking from",
    ctx: {
      toolName: "Write",
      filePath: "/repo/src/services/fresh.ts",
      content: OVER_ASK,
      files: {},
    },
    want: "ask",
  },
  {
    label: "a project-configured lower threshold asks sooner",
    ctx: {
      toolName: "Write",
      filePath: "/repo/src/services/mid.ts",
      content: linesOf(11),
      project: { limits: { fileLines: { warn: 5, ask: 10 } } },
    },
    want: "ask",
  },

  // negative — ordinary daily work
  { label: "a small file passes", ctx: { toolName: "Write", filePath: "/repo/src/small.ts", content: SMALL }, want: "pass" },
  {
    label: "a file over warn but under ask passes",
    ctx: { toolName: "Write", filePath: "/repo/src/mid.ts", content: UNDER_ASK },
    want: "pass",
  },
  {
    label: "a large .json file is skipped by extension",
    ctx: { toolName: "Write", filePath: "/repo/src/data.json", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a large .md file is skipped by extension",
    ctx: { toolName: "Write", filePath: "/repo/docs/notes.md", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a large .snap file is skipped by extension",
    ctx: { toolName: "Write", filePath: "/repo/src/__snapshots__/a.snap", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "yarn.lock is skipped",
    ctx: { toolName: "Write", filePath: "/repo/yarn.lock", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "pnpm-lock.yaml is skipped by name",
    ctx: { toolName: "Write", filePath: "/repo/pnpm-lock.yaml", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a file under dist/ is skipped as generated",
    ctx: { toolName: "Write", filePath: "/repo/dist/bundle.js", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a .generated. suffix file is skipped",
    ctx: { toolName: "Write", filePath: "/repo/src/api.generated.ts", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a file carrying an auto-generated header is skipped",
    ctx: {
      toolName: "Write",
      filePath: "/repo/src/weird.ts",
      content: `// <auto-generated>\n${OVER_ASK}`,
    },
    want: "pass",
  },
  {
    label: "a file under a notOurs path is skipped",
    ctx: { toolName: "Write", filePath: "/repo/cypress/e2e/huge.ts", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "empty content passes",
    ctx: { toolName: "Write", filePath: "/repo/src/empty.ts", content: "" },
    want: "pass",
  },
  {
    label: "no file path passes",
    ctx: { toolName: "Write", filePath: "", content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a shell command is not a file write and passes",
    ctx: { toolName: "Bash", command: "cat src/big.ts" },
    want: "pass",
  },

  // evasion
  {
    label: "backslash-separated notOurs path still recognised",
    ctx: { toolName: "Write", filePath: "C:\\repo\\cypress\\e2e\\huge.ts", cwd: "C:\\repo", git: { repoRoot: "C:\\repo" }, content: OVER_ASK },
    want: "pass",
  },
  {
    label: "a Codex-style apply_patch write is still asked",
    ctx: { toolName: "apply_patch", filePath: "/repo/src/services/big.ts", content: OVER_ASK },
    want: "ask",
  },

  // R3: a decoded MultiEdit/apply_patch update measures the whole
  // reconstructed file (ctx.resultingContent), never only what it inserts
  {
    label: "R3: a MultiEdit inserting a handful of lines still asks, measured against the true resulting size",
    ctx: {
      toolName: "MultiEdit",
      filePath: "/repo/src/services/big.ts",
      content: "const inserted1 = 1;\nconst inserted2 = 2;", // the write's own tiny inserted text
      resultingContent: OVER_ASK, // the whole file after the edit is applied
    },
    want: "ask",
  },
  {
    label: "R3: a MultiEdit whose own inserted text is huge but the true resulting file is small passes",
    ctx: {
      toolName: "MultiEdit",
      filePath: "/repo/src/small.ts",
      content: OVER_ASK, // would wrongly ask if content were measured instead of the whole file
      resultingContent: SMALL,
    },
    want: "pass",
  },

  // override
  {
    label: "an override softens the rule to pass",
    ctx: {
      toolName: "Write",
      filePath: "/repo/src/services/big.ts",
      content: OVER_ASK,
      overrideSpec: { "file-size-limit": { action: "off" } },
    },
    want: "pass",
  },

  // silent absent config
  {
    label: "a minimal project has nothing configured and a small file passes trivially",
    ctx: { toolName: "Write", filePath: "/repo/src/mid.ts", content: SMALL, project: PROJECT_MINIMAL },
    want: "pass",
  },
  {
    label: "requiresConfig: a minimal project with no limits.fileLines at all stays silent even well past any sane threshold — no invented default",
    ctx: { toolName: "Write", filePath: "/repo/src/services/big.ts", content: OVER_ASK, project: PROJECT_MINIMAL },
    want: "pass",
  },
  {
    label: "limits.fileLines present but missing an ask number stays silent rather than comparing against undefined",
    ctx: {
      toolName: "Write",
      filePath: "/repo/src/services/big.ts",
      content: OVER_ASK,
      project: { limits: { fileLines: { warn: 1000 } } },
    },
    want: "pass",
  },
];

suite("guards/file-size-limit", ({ test, eq }) => {
  for (const c of CASES) {
    test(c.label, () => {
      eq(decide(rule, c.ctx), c.want, c.label);
    });
  }
});
