"use strict";

/**
 * Table-driven suite for `no-edit-generated-docs`.
 */

const { suite } = require("../harness");
const { decide } = require("./_ctx");
const rule = require("../../core/guards/no-edit-generated-docs");

const GENERATED_CONTENT = [
  "# Frontend Architecture Standard",
  "",
  "> **Generated file — do not edit directly.** Produced by `tools/build-standard.js`",
  "> from the individual files in `docs/standards/`. Edit one of those and run",
  "> `node tools/build-standard.js` to regenerate this file, or",
  "> `node tools/build-standard.js --check` to verify it still matches without",
  "> writing anything.",
  "",
  "## Contents",
].join("\n");

const PART_CONTENT = [
  "# Naming",
  "",
  "Status: Active",
  "",
  "File, folder, hook, constant and spec naming conventions.",
].join("\n");

const ORDINARY_MARKDOWN = "# Notes\n\nJust an ordinary markdown file, not generated by anything.\n";

const GENERATED_PATH = "/repo/docs/standards/assembled/FRONTEND-ARCHITECTURE-STANDARD.md";
const PART_PATH = "/repo/docs/standards/naming.md";
const ORDINARY_PATH = "/repo/docs/notes.md";
const MISSING_PATH = "/repo/docs/standards/NEW-STANDARD.md";
const UNREADABLE_PATH = "/repo/docs/standards/CORRUPT-STANDARD.md";

const CASES = [
  // positive: a write lands on a file already carrying the generated marker
  {
    label: "a write to a generated standard document asks",
    ctx: { toolName: "Write", filePath: GENERATED_PATH, files: { [GENERATED_PATH]: GENERATED_CONTENT } },
    want: "ask",
  },
  {
    label: "an Edit tool call against a generated document still asks",
    ctx: { toolName: "Edit", filePath: GENERATED_PATH, files: { [GENERATED_PATH]: GENERATED_CONTENT } },
    want: "ask",
  },
  {
    label: "a Codex apply_patch call against a generated document still asks",
    ctx: { toolName: "apply_patch", filePath: GENERATED_PATH, files: { [GENERATED_PATH]: GENERATED_CONTENT } },
    want: "ask",
  },

  // negative — ordinary daily work
  {
    label: "a write to one of the source parts passes",
    ctx: { toolName: "Write", filePath: PART_PATH, files: { [PART_PATH]: PART_CONTENT } },
    want: "pass",
  },
  {
    label: "a write to an ordinary, non-generated markdown file passes",
    ctx: { toolName: "Write", filePath: ORDINARY_PATH, files: { [ORDINARY_PATH]: ORDINARY_MARKDOWN } },
    want: "pass",
  },
  {
    label: "a file that does not exist yet passes",
    ctx: { toolName: "Write", filePath: MISSING_PATH },
    want: "pass",
  },
  {
    label: "a file that cannot be read passes rather than crashing",
    ctx: { toolName: "Write", filePath: UNREADABLE_PATH },
    want: "pass",
  },
  {
    label: "a shell command is not a file write and passes even when it names a generated file",
    ctx: { toolName: "Bash", command: `cat ${GENERATED_PATH}` },
    want: "pass",
  },
  {
    label: "no file path passes",
    ctx: { toolName: "Write", filePath: "" },
    want: "pass",
  },

  // override
  {
    label: "an override can turn the rule off entirely",
    ctx: {
      toolName: "Write",
      filePath: GENERATED_PATH,
      files: { [GENERATED_PATH]: GENERATED_CONTENT },
      overrideSpec: { "no-edit-generated-docs": { action: "off" } },
    },
    want: "pass",
  },
];

suite("guards/no-edit-generated-docs", ({ test, eq }) => {
  for (const c of CASES) {
    test(c.label, () => {
      eq(decide(rule, c.ctx), c.want, c.label);
    });
  }
});
